name: jq-tset

on:
  workflow_dispatch:
  
  

jobs:
  simple_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.0

    - name: jq null tset
      id: jq_script
      run: |
        result=$(jq -r .RegionsBank1 config.json)
        if [[ "$result" == null ]]; then
          echo "Result is null"
        else
          echo "Result is not null"
        fi
      