name: python-test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  simple_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.0

    - name: Set up Python 3.8
      uses: actions/setup-python@v5.2.0
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # pip install -r requirements.txt

    - name: Run tests
      run: |
        python which python
