name: python-test

on:
  push:
    branches:
      - main

jobs:
  python_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.0

      - name: Set up Python 3.10
        uses: actions/setup-python@v5.2.0
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: call main.py
        env:
          BG_NAME: "BP"
        id: bg
        run: |
          python ${{ GITHUB.WORKSPACE }}/scripts/main.py
          ls -l

      - name: process output.json
        run: |
          # print the output.json file
          jq . output.json
          
          # iterate output.json to extract all "fgw_name", "days_to_expiry" from list in key "dev_instances"
          jq -r '.dev_instances[] | {fgw_name: .fgw_name, days_to_expiry: .days_to_expiry}' output.json

          
  




