name: python-test

on:
  push:
    branches:
      - main

jobs:
  python_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.0

      - name: Set up Python 3.10
        uses: actions/setup-python@v5.2.0
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: call main.py
        env:
          BG_NAME: "BP"
        id: bg
        run: |
          python ${{ GITHUB.WORKSPACE }}/scripts/main.py
          ls -l

      - name: process output.json
        run: |
          # print the output.json file
          #jq . output.json

          # Loop through each dev_instance entry in the JSON data
          jq -c '.dev_instances[] | {fgw_name, days_to_expiry}' output.json | while read -r instance; do
            # Extract "fgw_name" and "days_to_expiry" from each JSON object
            fgw_name=$(echo "$instance" | jq -r '.fgw_name')
            days_to_expiry=$(echo "$instance" | jq -r '.days_to_expiry')

            if [[ $days_to_expiry -lt 1000 ]]; then
              echo "The FortiGate instance $fgw_name has less than 30 days to expiry"
            else
              echo "The FortiGate instance $fgw_name has more than 30 days to expiry"
            fi
            echo "------------------------"
          done


          
  




