name: python-test

on:
  push:
    branches:
      - main

jobs:
  python_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.0

      - name: Set up Python 3.10
        uses: actions/setup-python@v5.2.0
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: -1- script with 2 numbers input and print result
        env:
          num1: 2
          num2: 3
        id: python_script
        run: |
          result=$(python ${{ GITHUB.WORKSPACE }}/scripts/main.py)
          echo "result -> $result"
      - name: -1- output
        run: |
          echo "Result: ${{ steps.python_script.outputs.result }}"

        # postman echo api test
      - name: Postman Echo API test
        id: postman_echo_api
        run: |
          python ${{ GITHUB.WORKSPACE }}/scripts/postman.py
      - name: display postman script output status code
        run: |
          echo "Status Code: ${{ steps.postman_echo_api.outputs.status_code }}"

        # business group process config with json file
      - name: process config.json file
        env:
          bg: "RegionsBank"
        id: process_json
        run: |
          python ${{ GITHUB.WORKSPACE }}/scripts/bg_json.py
      - name: display process config script output
        run: |
          echo "env_id: ${{ steps.process_json.outputs.env_id }}"

      # business group process config with json file
      # - name: process config.json file
      #   id: process_yaml
      #   run: |
      #     python ${{ GITHUB.WORKSPACE }}/scripts/bg_yaml.py
      # - name: display process config script output
      #   run: |
      #     echo "env_id: ${{ steps.process_yaml.outputs.env_id }}"
